version: 2.1

orbs:
  docker-publish: upenn-libraries/docker-publish@0.1.0

docker-publish: &docker-publish
  docker-publish/publish:
    context: quay.io
    registry: quay.io
    image: upennlibraries/jenkins_docker_client
    label_prefix: edu.upenn.library

workflows:
  build:
    jobs:
      - *docker-publish
  nightly_build:
    triggers:
      - schedule:
          cron: "0 4 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - *docker-publish
