version: 2.1

orbs:
  docker: circleci/docker@1.3.0
  slack: circleci/slack@3.4.2

docker-publish: &docker-publish
  docker/publish:
    context: quay.io
    extra_build_args: >-
      --label "edu.upenn.library.build-system=circleci"
      --label "edu.upenn.library.circleci.build-number=${CIRCLE_BUILD_NUM}"
      --label "edu.upenn.library.circleci.build-timestamp=$(date -uIs)"
      --label "edu.upenn.library.circleci.build-url=${CIRCLE_BUILD_URL}"
      --label "edu.upenn.library.circleci.git-branch=${CIRCLE_BRANCH}"
      --label "edu.upenn.library.circleci.git-commit=${CIRCLE_SHA1}"
      --label "edu.upenn.library.circleci.git-repo-url=${CIRCLE_REPOSITORY_URL}"
      --label "edu.upenn.library.circleci.workflow-id=${CIRCLE_WORKFLOW_ID}"
    image: upennlibraries/jenkins_docker_client
    post-steps:
      - run:
          name: Set Environment Variables for Slack Notification
          command: |
            echo "export GIT_COMMIT_DESC='$(git --git-dir $HOME/project/.git log --format=%B -n 1 $CIRCLE_SHA1)'" >> $BASH_ENV
            echo "export GIT_URL=<< pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>" >> $BASH_ENV
            source $BASH_ENV
      - slack/status:
          channel: tools-notifications
          failure_message: ":red_circle: Failure! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
          success_message: ":tada: Success! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
          webhook: ${SLACK_WEBHOOK}
    registry: quay.io
    tag: lts

workflows:
  build:
    jobs:
      - *docker-publish
  nightly_build:
    jobs:
      - *docker-publish
    triggers:
      - schedule:
          cron: "0 4 * * 0"
          filters:
            branches:
              only:
                - master
